# redis
spring:
  redis:
    database: 0   # 数据库索引，默认为0
    host: 192.168.237.128 # server host1
    #password: 123456 # 服务器连接密码（默认为空）
    port: 6379 #connection port
    # pool settings ...
    pool:
      max-idel: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
